Revert "MB-37956: Upgrade gsl-lite to v0.36"
This reverts commit 8c3ce30d001bbc5028fc851228ec1ca852b8332d.

Reason for revert: compilation error with Ubuntu 16.04 (verification was invalid, manifest change hadn't been picked up :(

    third_party/gsl-lite/include/gsl/gsl-lite.hpp: In instantiation of ‘struct gsl::detail::element_type_helper<const void*, void>’:
    third_party/gsl-lite/include/gsl/gsl-lite.hpp:1845:59:   required from ‘class gsl::not_null<const void*>’
    kv_engine/include/memcached/engine.h:180:63:   required from here
    third_party/gsl-lite/include/gsl/gsl-lite.hpp:1718:55: error: ‘const void*’ is not a pointer-to-object type
     typedef typename std::remove_reference< decltype( *std::declval<T>() ) >::type type;
                                                       ^~~~~~~~~~~~~~~~~~

Change-Id: I41e93b9621d1becaa88906d2159c68abf7cc4b7d
Reviewed-on: http://review.couchbase.org/c/manifest/+/130190
Reviewed-by: Dave Rigby <daver@couchbase.com>
Tested-by: Dave Rigby <daver@couchbase.com>